import { createHmac, timingSafeEqual } from "node:crypto";
import { cookies } from "next/headers";

const COOKIE = "cv_author";

/**
 * Is this request the site's author?
 *
 * Stage 1 uses a signed cookie derived from `CV_AUTHOR_SECRET`; Stage 2 replaces
 * the body with `payload.auth({ headers })`. Keeping it a single function is what
 * makes that a one-file change.
 *
 * Returns false when no secret is configured — an unconfigured deployment must
 * fail closed, hiding unpublished CVs rather than exposing them.
 */
export async function isAuthor(): Promise<boolean> {
  const secret = process.env.CV_AUTHOR_SECRET;
  if (!secret) return false;

  const token = (await cookies()).get(COOKIE)?.value;
  if (!token) return false;

  return safeEquals(token, expectedToken(secret));
}

/** The value to set as the `cv_author` cookie. Generated by `npm run author-token`. */
export function expectedToken(secret: string): string {
  return createHmac("sha256", secret).update(COOKIE).digest("hex");
}

function safeEquals(a: string, b: string): boolean {
  const bufA = Buffer.from(a);
  const bufB = Buffer.from(b);
  // timingSafeEqual throws on length mismatch, which would itself leak length.
  if (bufA.length !== bufB.length) return false;
  return timingSafeEqual(bufA, bufB);
}

/**
 * May this variant be served to the current request?
 *
 * Published variants are public. Everything else is author-only, and callers
 * must respond with 404 rather than 403 — a 403 confirms the slug exists, which
 * turns the route into an enumeration oracle for private CVs.
 */
export async function canServeVariant(published: boolean): Promise<boolean> {
  return published || (await isAuthor());
}
