import type { ExperienceGroup } from "@/types";
import type { CvFormat, CvVariant, SiteContent } from "@/types/cv";
import snapshotJson from "@/content/snapshot.json";
import type { ContentSnapshot } from "../snapshotShape";
import { pickPublished, type ContentSource } from "../types";

/**
 * The snapshot is generated by `scripts/generate-snapshot.mts` from live content,
 * so its shape is guaranteed by construction rather than by the type checker —
 * JSON imports widen to `string` and lose the literal unions. The contract test
 * is what actually holds this honest.
 */
const snapshot = snapshotJson as unknown as ContentSnapshot;

/**
 * Reads the committed `src/content/snapshot.json`.
 *
 * This is the fallback the circuit breaker falls through to when the CMS is
 * unreachable, and what `CONTENT_SOURCE=snapshot` selects deliberately. It is
 * bundled into the build artifact, so it needs no network or database at all.
 */
export const snapshotAdapter: ContentSource = {
  async getSiteContent(): Promise<SiteContent> {
    return snapshot.siteContent;
  },

  async getExperienceGroups(): Promise<ExperienceGroup[]> {
    return snapshot.experienceGroups;
  },

  async getCvVariants(): Promise<CvVariant[]> {
    return snapshot.cvVariants;
  },

  async getCvVariant(slug: string): Promise<CvVariant | null> {
    return snapshot.cvVariants.find((v) => v.slug === slug) ?? null;
  },

  async getPublishedVariant(format: CvFormat): Promise<CvVariant | null> {
    return pickPublished(snapshot.cvVariants, format);
  },
};

/** When the fallback content was last refreshed. Useful in logs and diagnostics. */
export const snapshotGeneratedAt = snapshot.generatedAt;
